### ISSUE TITLE
Moving documents to default folder if ZIO is deleted

### ISSUE THREAD

**Issue by SilviaAmAm** [open-zaak/cmis-adapter#32]
**Current behaviour**
When a document is related to a zaak, it is located in the zaak folder and has an OIO in the `Related Data` folder. If the ZIO relating the zaak and the document is deleted, the OIO is deleted, but the document remains in the zaak folder. 

**New desired behaviour**
1. If the document is NOT a copy, it should be moved to the default folder. If there are related gebruiksrechten, then they should also be moved.
2. If the document IS a copy, then it should be deleted. Related gebruiksrechten should also be deleted.

TODO:

- [x] Webservice binding 
- [x] Browser binding

**Comment by joeribekker** [comment]
Just to clarify how the Document API behaves with and without CMIS

![image](https://user-images.githubusercontent.com/96970/169770246-045f76ca-10a7-4c22-9ced-208d02384c20.png)
![image](https://user-images.githubusercontent.com/96970/169770267-7a22debb-a65e-4fb1-9748-6292ee91c058.png)
